features_hotspots = ['max_size',
 'avg_size',
 'median_size',
 'std_size',
 'total_patches',
 'percent_hotspot',
 'min_dist',
 'max_dist',
 'avg_dist',
 'nni',
 'spread_var',
 'region_density',
 'patch_density',
 'avg_prob_in_region',
 'prob_variance',
 'entropy_of_probs',
 'center_of_mass_x',
 'center_of_mass_y',
 'num_hotspots',
 'mean_contrast',
 'std_contrast',
 'high_contrast_percent',
 'laplace_mean',
 'laplace_std']

features_basic = ['mean_pos_prob',
 'mean_neg_prob',
 'mean_prob',
 'median_pos_prob',
 'median_neg_prob',
 'median_prob',
 'std_pos_prob',
 'std_neg_prob',
 'std_prob',
 'entropy_pos_prob',
 'entropy_neg_prob',
 'entropy_prob',
 'tas_pos_percent',
 'tas_neg_percent',
 'tas_pos_high_percent',
 'tas_conf_percent']

features_dist = ['mean_tas__1-2mm',
 'mean_tas__2-3mm',
 'mean_tas__3-4mm',
 'mean_tas__4-5mm',
 'mean_tas__5-6mm',
 'q95_tas__1-2mm',
 'q95_tas__2-3mm',
 'q95_tas__3-4mm',
 'q95_tas__4-5mm',
 'q95_tas__5-6mm',
 'burden_gt_tau__1-2mm',
 'burden_gt_tau__2-3mm',
 'burden_gt_tau__3-4mm',
 'burden_gt_tau__4-5mm',
 'burden_gt_tau__5-6mm',
 'patch_count__1-2mm',
 'patch_count__2-3mm',
 'patch_count__3-4mm',
 'patch_count__4-5mm',
 'patch_count__5-6mm',
 'tas_edge_core_ratio',
 'tas_com_distance',
 'tas_distance_entropy',
 'tas_lograte_slope',
 'tas_half_distance',
 'tas_total_mass',
 'tas_mean_rate_over_bins',
 'tas_max_rate_over_bins',
 'tas_rate_bin_1mm',
 'tas_rate_bin_2mm',
 'tas_rate_bin_3mm',
 'tas_rate_bin_4mm',
 'tas_rate_bin_5mm',
 'patch_count_bin_1mm',
 'patch_count_bin_2mm',
 'patch_count_bin_3mm',
 'patch_count_bin_4mm',
 'patch_count_bin_5mm',
]

features_graph = [
    'num_nodes', 'num_edges', 'avg_degree', 'clustering_coeff', 'graph_diameter', 'avg_shortest_path',
    'mean_betweenness','max_betweenness','std_betweenness','high_betweenness_count'
    
]